config/routes.rb
BizApp::Application.routes.draw do

  root 'restaurants#new'

  resources :users, except: [:destroy]

  resource :sessions, only: [:create, :new, :destroy]

  resources :restaurants

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	belongs_to :user
	validates_length_of :location, minimum: 1, maximum: 255
	validates_presence_of :category
	validates_presence_of :price
end

app/models/user.rb
class User < ActiveRecord::Base
	include ActiveModel::SecurePassword
	
	has_many :restaurants

	validates_presence_of :email,:password
	validates_uniqueness_of :email
   	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
   	validates_length_of :email, maximum: 255
   	validates_length_of :password, minimum: 6, maximum: 20

   	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
  	@current_user ||= User.where(id: session[:user_id]).first
  end
  def factual
    @factual = Factual.new("lbK0dTnbagtdHu4p7uh5mEZUQaogdPoXbsokyxde", "QLlJgvXdwX2quhXJbhKdVkDbGkyHzGz4Vv4vuPwA")
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  require 'factual'
  skip_before_filter :authorize

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
    render :json => Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @user = User.new
    @is_login = true
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    @user = User.new
    @is_login = true
    #@factual_data = factual.table("restaurants-us")
    #.geo("$point" => [34.012982, -118.495186])
    #.sort("$distance").page(1, :per => 5).rows
    # @factual_data = factual.table("restaurants-us")
    #.filters("locality" => "santa monica").page(2, :per => 20).rows
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @factual_data = factual.table("restaurants-us")
    .geo("$circle" => {"$center" => [@restaurant.latitude, @restaurant.longitude], "$meters" => 5000})
    .sort("$distance")
    .page(1, :per => 50).rows

    respond_to do |format|
      if @restaurant.save
        format.html {  }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:location, :category, :price, :latitude, :longitude)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_filter :authorize


	def new
		# Present an empty login form
		@user = User.new
		@is_login = true
	end

	def create
		# Find the user that is trying to log in		
		u = User.where(email: params[:user][:email]).first
		if u && u.authenticate(params[:user][:password])
			# Store as a cookie in the users' browser the ID of them,
			# indicating that they are logged in
			session[:user_id] = u.id.to_s
			redirect_to :root
		else
			# Go back to the login page
			redirect_to new_sessions_path
		end
	end

	def destroy
		reset_session
		redirect_to :root
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { 
          session[:user_id] = @user.id.to_s
          redirect_to :root
          # redirect_to @user, notice: 'User was successfully created.' 
        }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Predictive</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
      <style type="text/css">
      html, body, #map-canvas { height: 500px; margin: 0; padding: 0;};
      #map_canvas { height: 500px; margin: 0; padding: 0;}
    </style>
    
  <%= csrf_meta_tags %>

</head>
<body>
<%= yield %>
</body>
  <%= javascript_include_tag "application" %>
</html>

app/views/restaurants/_d3.html.erb
 <!-- D3 starts here -->
  <style type="text/css">

  div.bar{ 
    display: inline-block;
    width: 20px;
  /*  height: 75px;*/
    background-color: teal;
    margin-right: 2px;
  }

  body{
    text-align: center ;
  }
    </style>

  <script type="text/javascript">

  var w = 300;
  var h = 100;
  var barPadding = 1;
  // var padding = 20;


  var dataset = [(localStorage.trafficRating[1])*2.5, (localStorage.negativeRating[1])*2.5, (localStorage.positiveRating[1])*2.5];

  var labeldata = ["Traffic Score", "Competition Score", "Complement Score"];

 

  // Create SVG Element 
  var svg = d3.select("body")
  .append("svg")
  .attr("width", w)
  .attr("height", h);

  svg.selectAll("rect")
  .data(dataset)
  .enter()
  .append("rect")
  .attr("x", function(d, i){
    return i * (w / dataset.length);
  })
  .attr("y", function(d){
    return h - (d * 4);
  })
  .attr("width", w / dataset.length - barPadding)
  .attr("height", function(d){
    return d;
  })
  .attr("fill", function(d){
    return "rgb(0, 150, 0)";

  });

  // Create labels

  svg.selectAll("text")
  .data(labeldata)
  .enter()
  .append("text")
  .text(function(d){
    return d;
  })
  .data(dataset)
  .attr("x", 
    function(d, i){
    return i * (w / dataset.length) + (w / dataset.length - barPadding) / 2;
  })
  .attr("y", function(d){
    return h - (d * 4) + 14;
  })
  .attr("font-family", "Raleway")
  .attr("font-size", "10px")
  .attr("fill", "white")
  .attr("text-anchor", "middle");


  // d3.select("body")
  d3.selectAll("rect")
  .data(dataset)
  .attr("height", "0%")
  .transition()
  .duration(2000)
  .attr("height", "100%");

 

  </script>


  <!-- D3 ends here -->

app/views/restaurants/create.html.erb
<!-- Create page appears after a prediction is submitted -->

<!-- Variable in the span are for reference only -->
<span class="white_text" id='factual-data'>
<!-- This does not appear on the page -->
      <% @factual_data.each do |element| %>
        <%= element['name'] %>|
        <%= element['latitude'] %>|
        <%= element['longitude'] %>|
        <%= element['price'] %>|
        <%= element['rating'] %>|
        <%= element['cuisine'] %>|
      <% end %>
</span>

<!-- Runs a javascript file for creating a google map -->
<%= render 'createmap' %>

<!-- Code for elements that appear on the page starts here -->
<!-- Page header displays user information -->
<div class="sign_up">
  <!-- If the user is singned in display the username and a logout option -->
  <% if current_user %>
    <span class="white_text">
      <%= current_user.email %>
    </span>|<span class="white_text">
      <!-- 'Logout' link for full size view -->
      <%= link_to "LOGOUT", sessions_path, method: :delete, :style=>'color:#FFFFFF;' %>
    </span>
  <!-- If the user is not singned in display sign in and sign up options -->
  <% else %>
    <!-- Sign up link -->
    <a href="users/new" class="white_text" style="color: #fff;text-decoration: none;">SIGN UP</a>
    <span class="blue_text">|</span> 
    <!-- Login link -->
    <a href="sessions/new" class="white_text" style="color: #fff;text-decoration: none;">LOGIN</a>
  <% end %>
</div>
<!-- Home page link -->
<a href="/restaurants/new" class="new animated fadeIn" style="color: #fff;">HOME</a>

<!-- Page body begans here -->
<!-- Displays the page title -->
<h1 class="center main_title animated fadeInDown">PREDICTIVE</h1>
<!-- Overall rating title followed by the actual rating -->
  <h1 class="normal_font" id="overall">Overall Rating</h1>
  <p class="overall-rating"></p>

<!-- Additional rating information -->
<div class="ratings_holder">
  <div class="each-rating">
    <!-- <h3>Traffic<br>Score</h3> -->
    <div class='bar-chart'></div>
    <p class="rating"></p>
    Traffic
  </div>
  <div class="each-rating">
    <!-- <h3>Competition<br>Score</h3> -->
    <div class='bar-chart'></div>
    <p class="rating" ></p>
    Complement
  </div>
  <div class="each-rating">
    <!-- <h3>Complement<br>Score</h3> -->
    <div class='bar-chart'></div>
    <p class="rating"></p>
    Competition
  </div>
  <div class="each-rating">
    <!-- <h3>Complement<br>Score</h3> -->
    <div class='bar-chart'></div>
    <p class="rating"></p>
    Density
  </div> 
</div>
</br></br></br></br></br></br></br>
<!-- Displays recommendations -->
<div id="results" style="text-align: center; color: #fff;">
  <h2 style="padding-top:60px;">Recommendations</h2>
  <div class="recommendation"></div>
  <div class="recommendation"></div>
  <div class="recommendation"></div>
</div>

<!--     <span class="blue_text">LOCATION:</span>
    <%= @restaurant.location %><br> 

    <span class="blue_text">CATEGORY:</span>
    <%= @restaurant.category %><br> 

    <span class="blue_text">PRICE:</span>
    <%= @restaurant.price %> -->

<!-- Google map display -->
<br><br><div id="map-canvas" style="width:100%"></div>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Category</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.category %></td>
        <td><%= restaurant.price %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<!-- google maps api for map and geocoding -->
<%= render 'newmap' %>

<!-- authentication starts here -->
<div class="sign_up animated fadeIn">
  
  <% if current_user %>

    <!-- show current user's email if logged in -->
    <span class="white_text"><%= current_user.email %></span> | 

    <!-- 'Logout' link -->
    <span class="white_text">
      <%= link_to "LOGOUT", sessions_path, method: :delete, :style=>'color:#FFFFFF;' %>
    </span>

  <% else %>

    <!-- sign up link -->
    <a href="users/new" class="white_text" style="color: #fff;text-decoration: none;">SIGN UP</a>

    <span class="blue_text">|</span> 

    <!-- login link -->
    <a href="sessions/new" class="white_text" style="color: #fff;text-decoration: none;">LOGIN</a>

  <% end %>
</div>


<!-- Main app title -->
<h1 class="center main_title animated fadeInDown">
  PREDICTIVE</h1>

<!-- sub header -->
<h3 class="center sub_title animated fadeInDown" id="sub_title">YOUR GO-TO GUIDE FOR LOCAL BUSINESS SUCCESS PREDICTIONS</h3>

<!-- landing button -->
<a class="link_text animated fadeIn"><div id="landing_button" class="animated fadeInUp" onclick="displayForm()">Get Your Prediction</div></a>


<!-- map rendered here -->
<div id="form_map" class="animated fadeInUp">
  
<!-- error handling -->
<div class="new_form animated fadeInUp">
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<!-- main form for creating prediction -->

    <!-- Address field -->
    Address: 
    <%= f.text_field :location, placeholder: "Enter an Address or Click on the Map", :maxlength=>"254", :size=>"90", :id=>"coo" %><br><br>

    <!-- Category selection -->
    Category: 
    <%= f.select :category, [['Choose a category...'],['American','american'],['Bar','bar'],['BBQ','bbq'],['Breakfeast','breakfast'],['Burgers','burgers'],['Chinese','chinese'],['Cafe','cafe'],['Dessert','dessert'],['Diner','diner'],['French','french'],['Indian','indian'],['Italian','italian'],['Japanese','japanese'],['Mediterranean'],['Mexican','mexican'],['Sandwiches','sandwiches'],['Salads','salads'],['Seafood','seafood'],['Steakhouse','steakhouse']], id:'restaurant_category' %>
    <span class="price_label">

      <!-- Price range selection -->
      Price Range: 
      <%= f.select :price, [['$'],['$$'],['$$$'],['$$$$']], id:'restaurant_price' %>
    </span>

  <br><br>
  <div class="actions center">

    <!-- form submit button -->
    <%= f.submit "Check Success Rating", :class=>"submit get-rating" %>
  </div>

  <!-- hidden fields to pass lat/long to 'create.html.erb' -->
  <%= f.hidden_field :latitude, id: 'lat' %>
  <%= f.hidden_field :longitude, id: 'lng' %>

<% end %>
</div>

<!-- Map rendered here -->
<div id="map-canvas" class="animated fadeInUp"></div>
</div>

<!-- Basic javascript for getting various elements to appear/disappear -->
<script>
displayForm = function(){
      document.getElementById("landing_button").style.display = "none";
      document.getElementById("sub_title").style.display = "none";
      document.getElementById("form_map").style.display = 'inline';
    }
</script>

app/views/restaurants/show.html.erb
 <!-- google maps api -->
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvl41fmjeaBBlwgySDnKX7xPExYkID5ko">
</script>

 <script src="http://d3js.org/d3.v3.min.js" type="text/javascript" charset="utf-8"></script>

<!-- heatlayer library -->
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?libraries=visualization&sensor=true_or_false">
</script>

 <script type="text/javascript">
      var heatmap;
      var heatmapData = [
  {location: new google.maps.LatLng(34.017862, -118.4892), weight: -0.5},
  new google.maps.LatLng(34.013706, -118.4953),
  {location: new google.maps.LatLng(34.015661, -118.4919), weight: 2},
  {location: new google.maps.LatLng(34.018218, -118.4896), weight: 3},
  {location: new google.maps.LatLng(34.017084, -118.4936), weight: 2},
  new google.maps.LatLng(34.015422, -118.4901),
  {location: new google.maps.LatLng(34.015336, -118.4966), weight: 0.5},

  {location: new google.maps.LatLng(34.017211, -118.4939), weight: 3},
  {location: new google.maps.LatLng(34.02366, -118.4923), weight: 2},
  new google.maps.LatLng(34.013761, -118.4949),
  {location: new google.maps.LatLng(34.024381, -118.4921), weight: 0.5},
  new google.maps.LatLng(34.013878, -118.49517),
  {location: new google.maps.LatLng(34.014284, -118.4980), weight: 2},
  {location: new google.maps.LatLng(34.020093, -118.4974), weight: 3},
  {location: new google.maps.LatLng(34.02448, -118.4913), weight: 3},
  {location: new google.maps.LatLng(34.012684, -118.4960), weight: 3},
  {location: new google.maps.LatLng(34.014861, -118.4932), weight: 3},
  {location: new google.maps.LatLng(34.014472, -118.4983), weight: 3},
  {location: new google.maps.LatLng(34.017607, -118.49816), weight: 3},
  {location: new google.maps.LatLng(34.010373, -118.4933), weight: 3}
];
 function initialize() {
      var map;
      var elevator;
      var myOptions = {
          zoom: 13,
          center: new google.maps.LatLng(34.0500, -118.2500),
          mapTypeId: google.maps.MapTypeId.HYBRID,
          scrollwheel: false
      };


      map = new google.maps.Map($('#map-canvas')[0], myOptions);
      
    var pointArray = new google.maps.MVCArray(heatmapData);

      heatmap = new google.maps.visualization.HeatmapLayer({ data: pointArray});

        heatmap.setMap(map);


      var addresses = ['<%= @restaurant.location %>'];

      for (var x = 0; x < addresses.length; x++) {
          $.getJSON('http://maps.googleapis.com/maps/api/geocode/json?address='+addresses[x]+'&sensor=false', null, function (data) {
              var p = data.results[0].geometry.location
              var latlng = new google.maps.LatLng(p.lat, p.lng);
               
              var marker = new google.maps.Marker({
                  position: latlng,
                  map: map,
                  icon: '../../assets/marker1.png'
              });
              
              var infowindow = new google.maps.InfoWindow({
                content: '<%= @restaurant.location %>'
              });
              infowindow.open(map, marker);
        
              // google.maps.event.addListener(marker, 'click', function() {
              //   infowindow.open(map,marker);
              // });

              map.setCenter(latlng);

          });
      }
  };
  google.maps.event.addDomListener(window, 'load', initialize);
  google.maps.event.addDomListener(window, 'page:load', initialize);
  
  </script>

<!-- <p id="notice"><%= notice %></p>
 -->

    <div class="sign_up animated fadeIn">
      
      <% if current_user %>



          <span class="white_text"><%= current_user.email %></span> |           <!-- 'Logout' link for full size view -->
         <span class="white_text">
            <%= link_to "LOGOUT", sessions_path, method: :delete, :style=>'color:#FFFFFF;' %>
          </span>

      <% else %>

        <!-- sign up link -->
        <a href="users/new" class="white_text" style="color: #fff;text-decoration: none;">SIGN UP</a>

        <span class="blue_text">|</span> 

        <!-- login link -->
        <a href="sessions/new" class="white_text" style="color: #fff;text-decoration: none;">LOGIN</a>

      <% end %>
    </div>

<a href="/" class="new animated fadeIn" style="color: #fff;">HOME</a>

<h1 class="center main_title animated fadeInDown">PREDICTIVE</h1>

<!-- D3 starts here -->


<style type="text/css">

div.bar{ 
  display: inline-block;
  width: 20px;
/*  height: 75px;*/
  background-color: teal;
  margin-right: 2px;
}

body{
  text-align: center ;
}
  </style>
<body>

<script type="text/javascript">

var w = 500;
var h = 100;
var barPadding = 1;
// var padding = 20;


var dataset = [ 25, 7, 5, 22, 11, 8, 25, 14, 23, 19, 14, 11, 22, 23, 11, 13, 12, 17, 18, 10, 5, 18, 25, 9, 5];

// Create scale functions
// var xScale = d3.scale.linear()
// .domain([0, d3.max(dataset, function(d){
//   return d[0]; })])
// .range([padding, w - padding * 2 ]);

// var yScale = d3.scale.linear()
// .domain([0, d3.max(dataset, function(d){
//   return d[1]; })])
// .range([h - padding, padding]);

// var rScale = d3.scale.linear()
// .domain([0, d3.max(dataset, function(d){
//   return d[1]; })])
// .range([2, 5]);

// Define the x-axis

// var xAxis = d3.svg.axis()
// .scale(xScale)
// .orient("bottom");



// Create SVG Element 
var svg = d3.select("body")
.append("svg")
.attr("width", w)
.attr("height", h);

svg.selectAll("rect")
.data(dataset)
.enter()
.append("rect")
.attr("x", function(d, i){
  return i * (w / dataset.length);
})
.attr("y", function(d){
  return h - (d * 4);
})
.attr("width", w / dataset.length - barPadding)
.attr("height", function(d){
  return d * 4;
})
.attr("fill", function(d){
  return "rgb(" + (d * 10) + ", 0, 0)";

});

// Create x-axis

// svg.append("g")
// .call(xAxis);

// Create labels

svg.selectAll("text")
.data(dataset)
.enter()
.append("text")
.text(function(d){
  return d;
})
.attr("x", function(d, i){
  return i * (w / dataset.length) + (w / dataset.length - barPadding) / 2;
})
.attr("y", function(d){
  return h - (d * 4) + 14;
})
.attr("font-family", "sans-serif")
.attr("font-size", "11px")
.attr("fill", "white")
.attr("text-anchor", "middle");


// d3.select("body")
d3.selectAll("rect")
.data(dataset)
.attr("height", "0%")
.transition()
.duration(2000)
.attr("height", "100%");

</script>



</body>


<!-- D3 ends here -->

<div id="results">

  <div class="white_text">

  <h2>PREDICTION:</h2>

    <p class="rating"></p>

    <h2>RECOMMENDATIONS:</h2>


<!--     <span class="blue_text">LOCATION:</span>
    <%= @restaurant.location %><br> 

    <span class="blue_text">CATEGORY:</span>
    <%= @restaurant.category %><br> 

    <span class="blue_text">PRICE:</span>
    <%= @restaurant.price %> -->

  </div>


  <br><br><div id="map-canvas"></div>

</div>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

<script>
  /*Adjustable Variables*/
var distanceCoefficients = [];        //Array of distance coefficients
var categoryPriceCompetition = [0,9,2,0]; //Competition with the same category and price
var priceCompetition = [0,6,1,0];     //Competition with the same price range but different category
var categoryCompetition = [0,0,0,0];    //Competition with the same category but different price range
var complementaryEstabishment = [0,-3,1,0]; //Establishments with a different category and price rage
distanceCoefficients.push(
  categoryPriceCompetition,
  priceCompetition,
  categoryCompetition,
  complementaryEstabishment);

/*Program Variables*/
var output = 0;

/*Nameing Variables Do Not Change*/
var samePriceAndCategory = 0;
var samePriceOnly = 1;
var sameCategoryOnly = 2;
var differentPriceAndCategory = 3;
var lati = 0;
var lngi = 1;
var price = 2;
var cat = 3;

/*Temporary*/
var restaurant = 0;
var coffeeShop = 1;
var est = [];
est.push([34.025787,-118.483277,2,0]);
est.push([34.023690,-118.492328,2,0]);
est.push([34.028597,-118.486277,2,0]);
est.push([34.029111,-118.486358,1,0]);
est.push([34.020216,-118.496283,2,0]);
est.push([34.023857,-118.492100,2,0]);
est.push([34.016630,-118.491290,2,0]);
est.push([34.016828,-118.494929,1,1]);
est.push([34.023823,-118.483193,1,1]);
est.push([34.032964,-118.480940,1,1]);

rate = function(lat,lng,cost,category){
  var latitude = lat;
  var longitude = lng;
  var rating = 0;
  var distance = 0;
  var competitionType = 0;
  for(var i = 0; i < est.length; i++){
    distance = Math.sqrt(Math.pow(est[i][lati]-latitude,2)+Math.pow(est[i][lngi]-longitude,2));
    if(est[i][price] == cost && est[i][cat] == category){
      competitionType = samePriceAndCategory;
    }else if(est[i][price] == cost){
      competitionType = samePriceOnly;
    }else if(est[i][cat] == category){
      competitionType = sameCategoryOnly;
    }else{
      competitionType = differentPriceAndCategory;
    }
    rating -= distanceCoefficients[competitionType][0]
    rating -= distanceCoefficients[competitionType][1]*Math.pow(distance,(-1));
    rating -= distanceCoefficients[competitionType][2]*Math.pow(distance,(-2));
    rating -= distanceCoefficients[competitionType][3]*Math.pow(distance,(-3));
  }
  return rating;
};
output = (rate(34.019021,-118.496379,1,coffeeShop));
document.getElementsByClassName('rating')[0].innerHTML = output;
</script>

app/views/users/index.html.erb
<div class="white_text center">
  <% @users.each do |user| %>
      <%= user.email %> - <%= user.id %><br>
  <% end %>
</div>

app/views/users/new.html.erb
<br><br><br><br>
<h1 class="center">Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>